### ISSUE TITLE
Error when running `packaging_lumbar_rootlets/run_inference_single_subject.py`

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model-spinal-rootlets#73]
@RaphaSchl is getting the following error when running [packaging_lumbar_rootlets/run_inference_single_subject.py](https://github.com/ivadomed/model-spinal-rootlets/blob/main/packaging_lumbar_rootlets/run_inference_single_subject.py)

<details><summary>full error</summary>

```console
python [/home/raphaelle/model-spinal-rootlets/packaging_lumbar_rootlets//run_inference_single_subject.py](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/model-spinal-rootlets/packaging_lumbar_rootlets//run_inference_single_subject.py) -i [/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w.nii.gz](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w.nii.gz) -o [/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/for_rootlet_identif/AutoBinSeg_080824//sub-CTS01//sub-CTS01_ses-SPpre_acq-zoomit_T2w_rootlets_bin.nii.gz](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/for_rootlet_identif/AutoBinSeg_080824//sub-CTS01//sub-CTS01_ses-SPpre_acq-zoomit_T2w_rootlets_bin.nii.gz) -path-model [/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/for_rootlet_identif/Models/Dataset302_LumbarRootlets/nnUNetTrainer_1000epochs_NoMirroring__nnUNetPlans__3d_fullres](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/for_rootlet_identif/Models/Dataset302_LumbarRootlets/nnUNetTrainer_1000epochs_NoMirroring__nnUNetPlans__3d_fullres) -fold 0 -use-gpu
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.

Found [/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w.nii.gz](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w.nii.gz) file.
Creating temporary folder (/tmp/sciseg_prediction_2024-08-08_12-44-13_z5flx0r8)
Copied [/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w.nii.gz](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w.nii.gz) to [/tmp/sciseg_prediction_2024-08-08_12-44-13_z5flx0r8/sub-CTS01_ses-SPpre_acq-zoomit_T2w_0000.nii.gz](https://file+.vscode-resource.vscode-cdn.net/tmp/sciseg_prediction_2024-08-08_12-44-13_z5flx0r8/sub-CTS01_ses-SPpre_acq-zoomit_T2w_0000.nii.gz)
Using fold(s): [0]
Starting inference...it may take a few minutes...

perform_everything_on_device=True is only supported for cuda devices! Setting this to False
Running inference on device: cpu
Using checkpoint: checkpoint_final.pth
[/home/raphaelle/miniconda3/envs/venv_nnunet/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py:84](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/miniconda3/envs/venv_nnunet/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py:84): FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(join(model_training_output_dir, f'fold_{f}', checkpoint_name),
Traceback (most recent call last):
  File "/home/raphaelle/model-spinal-rootlets/packaging_lumbar_rootlets//run_inference_single_subject.py", line 251, in <module>
    main()
  File "/home/raphaelle/model-spinal-rootlets/packaging_lumbar_rootlets//run_inference_single_subject.py", line 198, in main
    predictor.initialize_from_trained_model_folder(
  File "/home/raphaelle/miniconda3/envs/venv_nnunet/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 100, in initialize_from_trained_model_folder
    network = trainer_class.build_network_architecture(
AttributeError: 'NoneType' object has no attribute 'build_network_architecture'
```

</details>

**Comment by valosekj** [comment]
@RaphaSchl, can you please try to remove `-use-gpu` flag? This flag is meant for CUDA NVIDIA GPUs? But I guess in your case you're running the model on CPU. Not using the `-use-gpu` flag, could solve the following part of the error message:

```console
perform_everything_on_device=True is only supported for cuda devices! Setting this to False
Running inference on device: cpu
```

**Comment by RaphaSchl** [comment]
Hi, I tried it without the flag and got the same exact error !

**Comment by valosekj** [comment]
I can also see that you're running the script from VSCode. Can you please try running the script directly from your terminal? Can you also run the following debug commands in your terminal?

```bash
conda activate nnunet     # change nnunet to other name if your env with nnunet is named differently 
pip freeze | grep nnunet
```

**Comment by RaphaSchl** [comment]
Same error when running commands directly in the terminal
The command `pip freeze | grep venv_nnunet` does not return anything, do you want me to list the packages that are in the env ?

**Comment by RaphaSchl** [comment]
Hey I tried using Dataset 322 (Dataset322_LumbarRootlets/nnUNetTrainer__nnUNetPlans__3d_fullres), 
instead of Dataset 302 No_Mirroring (Dataset302_LumbarRootlets/nnUNetTrainer_1000epochs_NoMirroring__nnUNetPlans__3d_fullres), and it worked !  

```
Found [/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop.nii.gz](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop.nii.gz) file.
Creating temporary folder (/tmp/sciseg_prediction_2024-08-08_13-57-33_2xlv5hdc)
Copied [/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop.nii.gz](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/Documents/PhantomPain/PhantomPainSpine/rawdata//sub-CTS01/ses-SPpre/anat/sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop.nii.gz) to [/tmp/sciseg_prediction_2024-08-08_13-57-33_2xlv5hdc/sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop_0000.nii.gz](https://file+.vscode-resource.vscode-cdn.net/tmp/sciseg_prediction_2024-08-08_13-57-33_2xlv5hdc/sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop_0000.nii.gz)
Using fold(s): [0]
Starting inference...it may take a few minutes...

perform_everything_on_device=True is only supported for cuda devices! Setting this to False
Running inference on device: cpu
Using checkpoint: checkpoint_final.pth
[/home/raphaelle/miniconda3/envs/venv_nnunet/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py:84](https://file+.vscode-resource.vscode-cdn.net/home/raphaelle/miniconda3/envs/venv_nnunet/lib/python3.9/site-packages/nnunetv2/inference/predict_from_raw_data.py:84): FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(join(model_training_output_dir, f'fold_{f}', checkpoint_name),
Model loaded successfully. Fetching data...
There are 1 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_raw is not defined and nnU-Net can only be used on data for which preprocessed files are already present on your system. nnU-Net cannot be used for experiment planning and preprocessing like this. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up properly.
nnUNet_preprocessed is not defined and nnU-Net can not be used for preprocessing or training. If this is not intended, please read documentation/setting_up_paths.md for information on how to set this up.
nnUNet_results is not defined and nnU-Net cannot be used for training or inference. If this is not intended behavior, please read documentation/setting_up_paths.md for information on how to set this up.

Predicting sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop:
perform_everything_on_device: False
100%|█████████████████████████████████████████████| 6/6 [01:19<00:00, 13.25s/it]
sending off prediction to background worker for resampling and export
done with sub-CTS01_ses-SPpre_acq-zoomit_T2w_crop
Inference done.
Total inference time: 1 minute(s) 47 seconds
```

**Comment by valosekj** [comment]
Okay! Thanks for testing the other model. I can see the reason now! `Dataset302_LumbarRootlets/nnUNetTrainer_1000epochs_NoMirroring__nnUNetPlans__3d_fullres` uses a custom trainer (`nnUNetTrainer_1000epochs_NoMirroring__nnUNetPlans__3d_fullres`), which I created by adding the following lines into the `./.conda/envs/nnunet/lib/python3.11/site-packages/nnunetv2/training/nnUNetTrainer/variants/training_length/nnUNetTrainer_Xepochs_NoMirroring.py` nnunet script. (I used `find . -name "nnUNetTrainer_*epochs_NoMirroring.py"` to get path to the file)

```python
class nnUNetTrainer_1000epochs_NoMirroring(nnUNetTrainer):
    def __init__(self, plans: dict, configuration: str, fold: int, dataset_json: dict, unpack_dataset: bool = True,
                 device: torch.device = torch.device('cuda')):
        super().__init__(plans, configuration, fold, dataset_json, unpack_dataset, device)
        self.num_epochs = 1000

    def configure_rotation_dummyDA_mirroring_and_inital_patch_size(self):
        rotation_for_DA, do_dummy_2d_data_aug, initial_patch_size, mirror_axes = \
            super().configure_rotation_dummyDA_mirroring_and_inital_patch_size()
        mirror_axes = None
        self.inference_allowed_mirroring_axes = None
        return rotation_for_DA, do_dummy_2d_data_aug, initial_patch_size, mirror_axes
```

**Comment by RaphaSchl** [comment]
No worries I'm glad we debugged it, thanks for your quick help :relieved:  I'll let you know how all this goes !
